# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f61178609bb656b55d299f1a5af70c0034ca84b0a914ab69f9383edbb51d3862b272fdd52063acbc548537636f192cdedb0e130e2213b6502f3a4d8a7ad1eb30

test:
  secret_key_base: c9faff9f821346163aef03309885d7071e5cdb5114741f7914cd3c8958b9733389186b960c3ab6b5a3d81d2d802cd08921d5a0b8ac027de29d50302e0b541c43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
